# Generated by Django 4.1.7 on 2023-03-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
