# Generated by Django 4.1.7 on 2023-03-01 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Cars', 'Cars'), ('Clothes', 'Clothes')], default='Food', max_length=25, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 1, 23, 54, 13, 423101, tzinfo=datetime.timezone.utc), verbose_name='creation'),
            preserve_default=False,
        ),
    ]
