# Generated by Django 4.1.7 on 2023-03-01 23:03

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('cpf_cnpj', models.CharField(max_length=14, verbose_name='cpf cnpj')),
                ('logo', models.FileField(blank=True, null=True, upload_to='', validators=[company.models.image_validator], verbose_name='logo')),
            ],
        ),
    ]
